### ISSUE TITLE
内容确实多了不少，我们一步一步，先从封页开始。

### ISSUE THREAD

**Issue by warycat** [warycat/iwa.life#24]
iwa.life 已经上线了。
大标题？
副标题？
按钮文字？
我还挑选了2个宝宝的图片，如果有其他的图片可以发给我。
中间的play button是一个视频，需选一个替换。

**Comment by zhuzj08** [comment]
![capture](https://cloud.githubusercontent.com/assets/13727330/9349446/05927408-45fb-11e5-97cb-782575c668a7.PNG)
这个图片为公司LOGO。
大标题：艾 娃  IWA
小标题： 携 - 艾娃之手 
                      让 - 美梦成真

**Comment by zhuzj08** [comment]
视频我还在重新录 录完给你发过去

**Comment by zhuzj08** [comment]
![144039394446579](https://cloud.githubusercontent.com/assets/13727330/9434154/736f612c-49f0-11e5-8a0a-4389ea261405.gif)

![144039705183626](https://cloud.githubusercontent.com/assets/13727330/9433897/3bc499a2-49ed-11e5-9d5f-6549672e3843.gif)
这两个字放在首页左上角处。LOGO暂时先不用放。
![capture](https://cloud.githubusercontent.com/assets/13727330/9433992/77fef204-49ee-11e5-98c6-e4bc0e18a49d.PNG)

Play button上面 写：携 - 艾娃之手。 让 - 美梦成真。

按键文字：开启未来。

首页背景图片你能不能从下面这个网站上照搬？
![5544645](https://cloud.githubusercontent.com/assets/13727330/9434268/d093a1b4-49f1-11e5-9460-76097f496bd8.PNG)

频文件我已经做好，如何发你？谢谢

**Comment by zhuzj08** [comment]
视频文件怎么给你？

**Comment by warycat** [comment]
视频可以穿在YouTube 上或者Vimeo

**Comment by zhuzj08** [comment]
视频地址在这里：<iframe src="https://player.vimeo.com/video/137112976" width="500" height="375" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> <p><a href="https://vimeo.com/137112976">艾娃首页视频</a> from <a href="https://vimeo.com/user43186900">zhijun zhu</a> on <a href="https://vimeo.com">Vimeo</a>.</p>

**Comment by warycat** [comment]
艾娃两个字太小，有毛边，我找不到你用的字体，到这个网站重新做一个。http://www.skyfont.com/
![_alpha_www skyfont com](https://cloud.githubusercontent.com/assets/1858099/9449268/5daca7ee-4a56-11e5-9077-24f34e99b22d.png)
字体大小选最大。

**Comment by warycat** [comment]
照片按照你的意思照搬了。看效果，还是很贴切的。

**Comment by zhuzj08** [comment]
他的动态照片 有几张我不需要的，其实我只要的是全家带着孩子，父母带着孩子和孩子自己一个人的这三张图片，可以修改一下吗？

**Comment by warycat** [comment]
改好了，这页基本就差不多了。如果logo字体要换可以告诉我。

**Comment by zhuzj08** [comment]
LOGO字体用 “方正准圆体”
![_www skyfont com](https://cloud.githubusercontent.com/assets/13727330/9840545/e8307d44-5a48-11e5-8c35-272c0d272a01.jpg)

**Comment by warycat** [comment]
![iwa](https://cloud.githubusercontent.com/assets/1858099/9894944/8bd867ea-5bde-11e5-8045-b22f270bb5da.png)
我把字体改到了透明白色，你可以看看在主页的效果怎样。

**Comment by warycat** [comment]
如果这个页面没有问题了，你可以close这个issue，我们就继续下一个。

**Comment by zhuzj08** [comment]
首页左上角的艾娃还是去掉，不要了。然后右上角的开启未来字体调大1号看看，中间的一行字调小一行

**Comment by warycat** [comment]
按照这个意思修改了，需要微调再告诉我。

**Comment by zhuzj08** [comment]
只要把开启未来这四个字稍微加粗，我觉得就行了

**Comment by warycat** [comment]
加粗了一点，如果觉得框和字之间距离大，可以考虑改成椭圆型。

**Comment by zhuzj08** [comment]
这个跟之前的相比差的有点多,能调小一点吗?还是小一号就是先前的尺寸?

**Comment by zhuzj08** [comment]
那个框能改吗？如果不能改就维持原样，然后我们进行下一页

Zhijun Zhu

Date: Fri, 18 Sep 2015 13:47:02 -0700

**Comment by warycat** [comment]
这个可以改的，之前是25px，现在改成22px。如果要再调整告诉我要多少px。

**Comment by zhuzj08** [comment]
第二页现状什么状态了？
